### ISSUE TITLE
레이아웃 변경 요청

### ISSUE THREAD

**Issue by ksree1021** [altair823/WordFinder#1]
검색해서 뜻이 나올 때 바짝 붙어있어요.
시작 부분에 여유가 있으면 좋겠네요~
![image](https://user-images.githubusercontent.com/86548143/123535826-7e8e8100-d761-11eb-957e-9d5fad8d4cd5.png)

**Comment by ksree1021** [comment]
검색창과 검색버튼을 붙이는 게 편할 듯요~~

**Comment by altair823** [comment]
0.5 버전부터 테마를 바꾸면서 해결되었다고 생각합니다
